### ISSUE TITLE
I ran into a problem when I ran the client code.

### ISSUE THREAD

**Issue by qishaoac** [drbild/sslpsk#5]
Traceback (most recent call last):
  File "server.py", line 33, in <module>
    main()
  File "server.py", line 30, in main
    server(host, port)
  File "server.py", line 18, in server
    hint='server1')
  File "C:\Python27\lib\site-packages\sslpsk\sslpsk.py", line 109, i
t
    sock.do_handshake()
  File "C:\Python27\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:661)

**Comment by drbild** [comment]
Perhaps this is the same issue as #3 and #1? 

I don't use Windows, so don't have a way to help debug Windows issues (other than ensuring that the automated build/test on Appveyor succeed).

**Comment by drbild** [comment]
Closing this since it's been inactive for over a year and no follow-up info was provided.
